[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173
  functions = "netlify/functions"

[functions."*"]
  # Increase timeout for enhanced AI chapter generation (8 minutes)
  timeout = "480s"
  # Increase memory for larger, high-quality responses
  memory = "1536MB"

[functions."autoGenerateNovel"]
  # Maximum timeout for full novel generation (15 minutes)
  timeout = "900s"
  # Maximum memory for complex processing
  memory = "3008MB"
