[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173
  functions = "netlify/functions"

[functions]
  # Increase timeout for AI generation functions (5 minutes)
  timeout = 300
  # Increase memory for larger responses
  memory = 1024
